## Dynamic control SMA inverter automation
input_boolean:
  dynamic_control_bool:
    name: "Dynamic control SMA"
    icon: mdi:transmission-tower-export
    #initial: off

input_number:
  dynamic_price_limit:
    name: "Dynamic price limit"
    initial: -0.01
    min: -0.2
    max: 0.3
    step: 0.01
    unit_of_measurement: ""
    icon: mdi:currency-eur
    mode: box

automation:
  id: dynamic_control_inverter
  alias: Dynamic control inverter
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.current_electricity_price     #choose 'Frank Energy' for example (hacs instal)
    id: new_price
  - platform: state
    entity_id: input_boolean.dynamic_control_bool
    from: 'on'
    to: 'off'
    id: return_to_100
  action:
  - variables:
      dynamic_price_limit: '{{ states("input_number.dynamic_price_limit") | float }}'
      sma_slider_entity: input_number.sma_power_limit_slider  
      #multiple inverter change to [ input_number.sma_power_limit_slider_1, input_number.sma_power_limit_slider_2 ]
      dynamic_price: '{{ states("sensor.current_electricity_price") |float (default=0) }}'
  - choose:
    - conditions:
      - condition: trigger
        id:
        - new_price
      - condition: state
        entity_id: input_boolean.dynamic_control_bool
        state: 'on'
      - condition: template
        value_template: '{{ dynamic_price > dynamic_price_limit }}'
      sequence:
      - service: input_number.set_value
        data_template:
          entity_id: '{{ sma_slider_entity }}'
          value: 100
    - conditions:
      - condition: trigger
        id:
        - new_price
      - condition: state
        entity_id: input_boolean.dynamic_control_bool
        state: 'on'
      - condition: template
        value_template: '{{ dynamic_price < dynamic_price_limit }}'
      sequence:
      - service: input_number.set_value
        data_template:
          entity_id: '{{ sma_slider_entity }}'
          value: 0
    - conditions:
      - condition: trigger
        id:
        - return_to_100
      sequence:
      - service: input_number.set_value
        data_template:
          entity_id: '{{ sma_slider_entity }}'
          value: 100
  mode: single