## Feedback control with 1 SMA inverter automation
input_boolean:
  feedback_control_bool:
    name: "Feedback control SMA"
    icon: mdi:transmission-tower-export
    #initial: off

automation:
  id: feedback_control_sma
  alias: Feedback control SMA
  description: ""
  mode: parallel
  max_exceeded: silent
  trigger:
  - platform: state
    entity_id:
      - sensor.p1_meter_active_power
    from: null
    id: feedback
  - platform: state
    entity_id: input_boolean.feedback_control_bool
    from: 'on'
    to: 'off'
    id: return_to_100
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.feedback_control_bool
        state: 'on'
      sequence:
      - service: input_number.set_value
        metadata: {}
        data:
          value: >-
            {% set p_max = 5.000 -%}
            {% set p_meter = states('sensor.p1_meter_active_power')|float(default=p_max) / 1000 -%}
            {% set sma = states('sensor.sma_actueel')|float(default=p_max * 1000) / 1000 -%}
            {% set s = p_max / 100 -%}
            {% set n = ((sma + p_meter) / s) -%}
            {{ max( min(n, 100), 0)|round(0, 'ceil') }}
        target:
          entity_id: input_number.sma_power_limit_slider
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
    - conditions:
      - condition: trigger
        id:
        - return_to_100
      sequence:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.sma_power_limit_slider
          value: 100
